

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members=["matrix", "assert_type_eq"]
#members=[ "augmented_random_search",  "matrix", "fetch_alpha_vantage"]
